### ISSUE TITLE
Flex does not update symfony.lock

### ISSUE THREAD

**Issue by HEKET313** [symfony/flex#347] opened 2018-04-05 13:02 UTC
As soon as I execute composer install without vendor directory all my dependencies downloads and configures, but symfony.lock contains only empty array.
In my project I don't need all files and configs that are created by doctrine bundles or routing so I remove them. But next time when anybody else will download my repo and execute `composer install` all this packages will be configured again. Also command `composer fix-recipes` configures again all this packages.
As soon as I add this packages to symfony.lock everything works like a charm

I'm using following packages:
symfony/translation
doctrine/annotations
doctrine/doctrine-bundle
doctrine/doctrine-cache-bundle
doctrine/doctrine-fixtures-bundle
optimax/test-bundle
phpunit/phpunit
sensiolabs/security-checker
symfony/web-server-bundle

But if I add this packages to symfony.lock and execute `composer fix-recipes` this file changes and versions of this packages becomes right also recipes don't apply anymore

**UPD**: Version of symfony/flex is 1.0.78

**Comment by xabbuh** [comment] 2018-04-05 13:18
Did you start your project before the introduction of the `symfony.lock` file? The goal of this file is precisely to avoid applying a recipe multiple times. So after it's been applied, there should an entry for that package in the lock file and you should be able to delete and modify any file that was created by the recipe.

**Comment by HEKET313** [comment] 2018-04-05 13:25
Yea, sure. I've created my project with `composer create-project symfony/skeleton` and all this dependencies was required via `composer require`. Before editing symfony.lock I've tried `remove` and `require` them several times.

**Comment by xabbuh** [comment] 2018-04-05 13:29
Could you provide a set of steps we could perform to reproduce the behaviour you experience?

**Comment by HEKET313** [comment] 2018-04-05 13:59
I found root of the problem. One of steps is that in our company we use this project: https://github.com/composer/satis for storing our repositories. So steps are following:
1. `composer create-project symfony/skeleton flex-test`
2. `cd flex-test`
3. Add following lines to `composer.json`:
`
"repositories": [
        {
            "type": "composer",
            "url": "our satis url"
        }
    ],
`
4. `composer require --dev phpunit/phpunit`
After this phpunit are configured but is not added to `symfony.lock`
If I remove `repositories` entry from composer.json phpunit is added to `symfony.lock` as it should added.

**Comment by nicolas-grekas** [comment] 2020-12-15 17:01
I'm closing because this staled. If you run into the issue, please try submitting a fix as you might be in the best position to debug what happens.

**Closed by nicolas-grekas** 2020-12-15 17:01 UTC
