### ISSUE TITLE
[Bug] The "profiler" installation fails because of some "twig" error

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/flex#24] opened 2017-04-03 18:34 UTC
In a fresh Symfony app created with Flex:

```
$ composer require profiler

Using version ^3.3@dev for symfony/web-profiler-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 4 installs, 0 updates, 0 removals
  - Installing symfony/var-dumper (dev-master b7864e4): Downloading (100%)
  - Installing twig/twig (2.x-dev 84dea31): Loading from cache
  - Installing symfony/twig-bridge (dev-master 8b7855d): Loading from cache
  - Installing symfony/web-profiler-bundle (dev-master 086d0a7): Downloading (100%)
    Detected auto-configuration settings for "symfony/web-profiler-bundle"
    Enabling the package as a Symfony bundle
    Setting configuration and copying files
Writing lock file
Generating autoload files
Executing script make cache-warmup [OK]
Executing script assets:install --symlink --relative %WEB_DIR% [KO]
 [KO]
Script assets:install --symlink --relative %WEB_DIR% returned with error code 1
!!
!!
!!
!!    [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
!!    The service "web_profiler.controller.profiler" has a dependency on a non-ex
!!    istent service "twig".
!!
!!
!!
!!

Installation failed, reverting ./composer.json to its original content.
```

**Comment by fabpot** [comment] 2017-05-27 16:54
duplicate of #90

**Closed by fabpot** 2017-05-27 16:54 UTC
Labels: bug

**Comment by stof** [comment] 2018-11-07 16:39
this has been fixed in newer versions of WebProfilerBundle by depending on TwigBundle, as that was the best fix actually. If you are still on a version without the requirement, the easiest solution is to install TwigBundle too (and then, you can decide to enable it only in dev instead of enabling it in all environments as done in the TwigBundle recipe if you don't need it for anything else)
