### ISSUE TITLE
Disabling the recipes for CI builds

### ISSUE THREAD

**Issue by sroze** [symfony/flex#223] opened 2017-12-03 20:02 UTC
I just got a deployment breaking a deployed environment because a recipe was installed when running `composer install` within the deployment pipeline. I guess it used a recipe that wasn't here before the last time I ran `composer *`, therefore installed _things_ and it broke... 🤔 

Is there any way to force not installing the recipes for the CI build? If not, would an environment variable be good in your PoV?

**Comment by sroze** [comment] 2017-12-04 08:58
To prevent such issue (i.e. running the recipes and overriding some of my files at build time), I had to `rm -rf vendor && composer install` locally.

**Comment by B-Galati** [comment] 2017-12-04 09:10
Your `symfony.lock` was committed ?

**Comment by sroze** [comment] 2017-12-04 09:22
@B-Galati yep, it is.

**Comment by stof** [comment] 2017-12-04 09:32
May it be that you started to install packages in your project before Flex introduced the lock file, and so some packages were not locked properly ?

**Comment by sroze** [comment] 2017-12-04 09:36
I had the symfony.lock file already, so it was after(ish). I think you are right where maybe when Flex's lock was introduced, it only wrote the `symfony.lock` file with the packages I installed later.

But, the alternative option, **the most worrying one**, some recipes were introduced after I `composer req [package]`, therefore `composer install` applied the recipe because it wasn't in the `symfony.lock` ? 🤔

**Comment by fabpot** [comment] 2017-12-04 16:28
Projects started before the introduction of the lock might have some issues. I'm closing as the use case you mention was indeed not working. But fixed with the lock. If that's not the case, please give us with a script that reproduces the issue and I will have a look. Thanks.

**Closed by fabpot** 2017-12-04 16:28 UTC

**Comment by k00ni** [comment] 2020-06-12 13:10
**For the sake of documentation:** *For people working with Flex day-to-day it may be obvious, but as a developer only using it if necessary, it cost me quite some time to figure it out:* 

If you run `composer update` in your CI (like Travis or Github Action) with `symfony.lock` **not** committed in Git, composer will install Symfony recipes every time. I used `phpunit-bridge` and it always created `tests/bootstrap.php` for instance (my php-cs-fixer command failed because of that file).

Might also be helpful in this regard: https://github.com/symfony/flex/issues/379#issuecomment-462239179

**If you want to replicate the status you have locally:**
* run `composer install` when installing dependencies in CI
* commit `composer.lock`
* commit `symfony.lock`

**Comment by fabpot** [comment] 2020-06-12 13:41
You **must** commit `symfony.lock`.
