### ISSUE TITLE
Flex is not compatible with composer shipped with Debian

### ISSUE THREAD

**Issue by sroze** [symfony/flex#205] opened 2017-11-14 10:30 UTC
I guess we need some documentation as it causes issues for Debian-based developers :/

**Comment by xabbuh** [comment] 2017-11-14 10:43
What exactly is the issue with the Composer version shipped by Debian?

**Comment by stof** [comment] 2017-11-14 11:50
According to https://packages.debian.org/search?keywords=composer, the issue is that Debian stable ships composer 1.2.2, which is indeed too old to be supported by the Flex plugin.

But I think the issue here is the usage of this unofficial Debian package. Using this package is not an installation way supported by the Composer team, and it leads to using an old version of Composer.
composer 1.2.2 was released in November 2016, and lots of improvements and bug fixes have been done since then.

**Comment by sroze** [comment] 2017-11-14 13:23
Completely agree with you @stof, it should not be used. Really is (here in our SfCon workshop) a lot of the users had the Debian system composer installed, therefore `composer create-project` failed badly without a very helpful message.

Ideally, we should have the Flex plugin allow to be installed but display a user-friendly exception. If we can't, a nice documentation warning :)

**Comment by Pierstoval** [comment] 2017-11-14 15:53
What does a `composer selfupdate` do when using the one shipped with Debian?
If it works, it could be a very neat and fancy solution...

**Comment by sroze** [comment] 2017-11-14 16:04
Unfortunately, the self-update is not available in the version shipped with
Debian

**Comment by dunglas** [comment] 2017-11-15 06:04
The version shipped with the current Ubuntu LTS is 1.0.0~beta2-1 (https://packages.ubuntu.com/xenial/composer) and it's the one that was mainly used during the workshop.

**Comment by dunglas** [comment] 2017-11-15 06:46
I don't think there is something we can do beside mentioning what to do when this error occurs in the documentation.

**Comment by fabpot** [comment] 2017-11-18 08:39
Closing as I don't see what can be done here.

**Closed by fabpot** 2017-11-18 08:39 UTC
