### ISSUE TITLE
Removing test-pack deletes config/bootstrap.php

### ISSUE THREAD

**Issue by zorn-v** [symfony/flex#498] opened 2019-05-11 15:01 UTC
I did not find something in recipes so direct me.

Also I did not find variant to restore it except as `git checkout`.

**Comment by nicolas-grekas** [comment] 2019-05-11 15:19
Which version of flex?  This should be fixed with recent ones - but it needs a symfony.lock generated by such recent version.
Try composer sync-recipes

**Comment by zorn-v** [comment] 2019-05-11 15:22
The latest one.
```
            "name": "symfony/flex",
            "version": "v1.2.5",
```

**Comment by zorn-v** [comment] 2019-05-11 15:23
Anyway - removing bootstrap.php MUST be forbidden I think

**Comment by zorn-v** [comment] 2019-05-11 15:33
> Try composer sync-recipes

Empty output (and no bootstrap.php of cause) on HEAD^1

**Comment by nicolas-grekas** [comment] 2019-05-11 16:30
you need to remove symfony.lock before running the command

**Comment by zorn-v** [comment] 2019-05-11 16:59
Yep, its worked. But is not a bug ?

**Comment by zorn-v** [comment] 2019-05-11 17:03
Anyway, thanks for hint about removing symfony.lock

**Comment by nicolas-grekas** [comment] 2019-05-11 17:04
Not a bug: that won't happen with symfony.lock files written by recent enough flex.
If I'm wrong, please provide a reproducer!

**Comment by zorn-v** [comment] 2019-05-11 17:14
If you have old `symfony.lock` (and you dont know about it), you must suffer ? 😄 
I think it is a bug (maybe not critical).

**Comment by nicolas-grekas** [comment] 2019-05-11 17:20
It is - but it's a fixed one :)

**Comment by zorn-v** [comment] 2019-05-11 17:24
But without BC 😄 
You need to remoce symfony.lock

**Closed** 2019-06-04 12:12 UTC

**Comment by stof** [comment] 2019-06-04 12:48
Well, the thing is, the fix involved writing more info to the lock file to identify that multiple recipes wanted this file (previously, other recipes would ignore the file)

**Comment by leongersen** [comment] 2019-06-09 07:07
This is still an issue (flex 1.2.6). After setting up a new project using `symfony/website-skeleton` yesterday, flex still ends up removing `bootstrap.php`, even after removing `symfony.lock` and running `composer sync-recipes`.

```
composer remove symfony/test-pack --dev
```

```
Symfony operations: 1 recipe (384ceb3ec6e2d26febf0613bdf385b73)
  - Unconfiguring symfony/phpunit-bridge (>=4.3): From github.com/symfony/recipes:master
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!
!!  Warning: require(C:\System\cosmos/config/bootstrap.php): failed to open stream
```
