### ISSUE TITLE
Error during installation of recipe does not revert everything back

### ISSUE THREAD

**Issue by nesl247** [symfony/flex#194] opened 2017-10-24 19:37 UTC
I discovered this when I was dealing with https://github.com/symfony/symfony/issues/24683. The issue is that if you install a recipe, and an error occurs for any reason, any generated files are not removed, nor is `.gitignore` and `composer.lock` reverted back to it's original state.

**Comment by weaverryan** [comment] 2017-10-25 20:16
I’ve also hit this issue, typically in a similar way - i.e. cache clear fails, then things are partially reverted.

Would the desired behavior be to fully uninstall the recipes?

**Comment by nesl247** [comment] 2017-10-25 21:06
That would be my expected outcome. If it fails to install, revert all changes made by the recipe. I'm gonna guess this isn't possible though because the script that is being run is run after flex has already performed it's changes.

**Comment by fabpot** [comment] 2017-10-26 16:19
closing as a duplicate of #142

**Closed by fabpot** 2017-10-26 16:19 UTC
