### ISSUE TITLE
Installing packs can lead to dependencies both in require and require-dev

### ISSUE THREAD

**Issue by dunglas** [symfony/flex#674] opened 2020-08-28 20:45 UTC
I installed the api, orm, debug and profiler packs, and I ended with `twig-bundle` both in the `require` and `require-dev` sections.
If a package is already present in the `require` section, it shouldn't be added to `require-dev`.

**Comment by lyrixx** [comment] 2020-08-28 21:27
Duplicate of https://github.com/symfony/flex/issues/654 ?

**Closed** 2020-08-29 06:45 UTC

**Comment by weaverryan** [comment] 2020-08-29 15:56
Actually, I think duplicate of #597, which nicely has a PR #673. But I also still want #654 :)
