### ISSUE TITLE
flex not updating existing package.json ( webpack-encore-bundle install )

### ISSUE THREAD

**Issue by hellomedia** [symfony/flex#827] opened 2021-11-02 14:19 UTC
I installed `webpack-encore-bundle 1.12` on a sf 5.3 project after updating it from 2.8 , with `flex 1.17.2`

The recipe updated / created files correctly, except for the existing  `package.json`, which was not updated.

I then removed both encore and my existing `package.json`. After that, installing encore added `package.json` successfully.

Is this a known limitation ?

NB: Not sure if it might be related, but I notice the recipe version given by `composer recipes`, 1.12, does not exist

```
$ hk ./composer.phar recipes symfony/webpack-encore-bundle
name             : symfony/webpack-encore-bundle
version          : 1.12
status           : up to date
installed recipe : https://github.com/symfony/recipes/tree/master/symfony/webpack-encore-bundle/1.12
files            : 
```
Latest recipe for webpack-encore seems to be 1.9 : 
https://github.com/symfony/recipes/tree/master/symfony/webpack-encore-bundle
Broken link to 1.12 :
https://github.com/symfony/recipes/tree/master/symfony/webpack-encore-bundle/1.12

**Comment by nicolas-grekas** [comment] 2021-11-23 11:10
Thanks, I fixed the wrongly reported version number in 3f0dc66
About the file not being updated, I think that's expected since flex does overrides existing files.
Closing therefor. Please provide a reproducer with instructions if you still think there is a bug.

**Closed by nicolas-grekas** 2021-11-23 11:10 UTC
