### ISSUE TITLE
Flex updates composer.lock when running composer install

### ISSUE THREAD

**Issue by fbourigault** [symfony/flex#523] opened 2019-06-26 15:17 UTC
I upgraded to symfony/flex 1.3.0 and now, when I install dependencies in an empty project (CI), the composer.json file is modified :fearful:

With Flex:
```
# composer install --no-progress --no-suggest             
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 216 installs, 0 updates, 0 removals
  - Installing symfony/flex (v1.3.0): Loading from cache
Loading composer repositories with package information
Updating dependencies (including require-dev)                 
Restricting packages listed in "symfony/symfony" to "4.2.*"
Package operations: 215 installs, 0 updates, 0 removals
[...]
Writing lock file
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [OK]
Executing script assets:install public [OK]

# git status
On branch feature/update-dependencies
Your branch is up to date with 'origin/feature/update-dependencies'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   composer.lock

no changes added to commit (use "git add" and/or "git commit -a")

# git diff
diff --git a/composer.lock b/composer.lock
index 4c42b16f..e0f70875 100644
--- a/composer.lock
+++ b/composer.lock
@@ -11107,7 +11107,7 @@
                     "homepage": "https://nette.org/contributors"
                 }
             ],
-            "description": "🔍 Nette Finder: find files and directories with an intuitive API.",
+            "description": "? Nette Finder: find files and directories with an intuitive API.",
             "homepage": "https://nette.org",
             "keywords": [
                 "filesystem",
@@ -11167,7 +11167,7 @@
                     "homepage": "https://nette.org/contributors"
                 }
             ],
-            "description": "🍸 Nette NEON: encodes and decodes NEON file format.",
+            "description": "? Nette NEON: encodes and decodes NEON file format.",
             "homepage": "http://ne-on.org",
             "keywords": [
                 "export",

```

Without Flex:
```
# composer install --no-progress --no-suggest --no-plugins
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 216 installs, 0 updates, 0 removals
[...]
Generating autoload files
> symfony-cmd
sh: symfony-cmd: command not found
Script symfony-cmd handling the auto-scripts event returned with error code 127
Script @auto-scripts was called via post-install-cmd
exit status 127

# git status                                       
On branch feature/update-dependencies
Your branch is up to date with 'origin/feature/update-dependencies'.

nothing to commit, working tree clean
```

**Comment by bendavies** [comment] 2019-06-26 16:23
Came here to submit the same issue.

reproducer:
https://gist.github.com/bendavies/90b7cd7892b9b69a26e995750ee280a7

**Comment by nicolas-grekas** [comment] 2019-06-26 18:18
@bendavies I tried your gist, it looks unrelated to this issue, and unrelated to flex also: `composer up --no-scripts --no-plugins` doesn't work either, and the same happens after `composer remove symfony/flex`:
```
  Problem 1
    - ocramius/doctrine-batch-utils dev-master requires php ^7.3.0 -> your PHP version (7.2.19) does not satisfy that requirement.
    - ocramius/doctrine-batch-utils dev-master requires php ^7.3.0 -> your PHP version (7.2.19) does not satisfy that requirement.
    - Installation request for ocramius/doctrine-batch-utils dev-master#97eebe837513b3014bb723237cd1e1bde8603364 -> satisfiable by ocramius/doctrine-batch-utils[dev-master].
```

**Comment by nicolas-grekas** [comment] 2019-06-26 18:23
@fbourigault please provide any reproducer, I cannot generate a .lock with the magnifying glass. An empty project that requires only nette/finder, without flex anywhere generates the `?` directly.

**Comment by bendavies** [comment] 2019-06-26 18:52
@bendavies that's because of this.
I still think this is a flex issue. please see the better reproducer:
https://gist.github.com/bendavies/90b7cd7892b9b69a26e995750ee280a7

**Comment by fbourigault** [comment] 2019-06-26 20:54
It looks like the question mark instead of the magnifying glass is an composer issue. If you look at http://repo.packagist.org/p/nette/finder%243ddbc140b41df41f492131ad1e31c87886ff2b7f7e5e145b38b9a827ea424194.json you got some question marks.

This question mark vs magnifying glass problem is just showing us that flex is modifying the composer.lock file when running composer install.

I think this must not happen.

**Comment by nicolas-grekas** [comment] 2019-06-27 08:11
Fixed in https://github.com/symfony/flex/commit/20951ca6a9d81e56cdf22263b61ae9abe08c94de
Thanks @bendavies for the reproducer.

**Closed by nicolas-grekas** 2019-06-27 08:11 UTC
