### ISSUE TITLE
Reading flex.symfony.com on composer install when composer.lock and symfony.lock files are present (same as #527)

### ISSUE THREAD

**Issue by domainfun** [symfony/flex#896] opened 2022-04-11 11:06 UTC
I'm not sure how Flex works internally, but I understand from ticket https://github.com/symfony/flex/issues/527 that Composer should NOT be retrieving the empty JSON https://flex.symfony.com/versions.json (which by the way has a missing POSIX line ending).

_We have recently upgraded Composer using:_

```text
$ composer self-update --2
Updating to version 2.3.3 (2.x channel).
   Downloading (100%)
Use composer self-update --rollback to return to version 1.10.25
```

_Ever since then Composer is broken, the initial error was:_

```text
$ composer install --no-dev --optimize-autoloader --prefer-dist --dry-run
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.

In CurlDownloader.php line 613:

  The "https://flex.symfony.com/versions.json" file could not be downloaded (HTTP/2 520 )
```

I don't know what "520 " means, but presumably the web server https://flex.symfony.com/ was simply busy or unavailable.

_Any subsequent attempts to run `composer install` always return this:_

```text
$ composer install --no-dev --optimize-autoloader --prefer-dist --dry-run
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.

In PackageFilter.php line 125:

  Undefined index: splits
```

So my conclusion is that Composer appears to read the empty JSON from https://flex.symfony.com/versions.json and then complains that it cannot process the non-existing content, even though Composer should actually be using the JSON from our lock files.

For clarification, both `composer.lock` and `symfony.lock` are present and are valid JSON, and Composer seems to be installed correctly:

```text
$ composer --version
Composer version 2.3.3 2022-04-01 22:15:35
```

... and ...

```text
$ composer diagnose
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.3.3
PHP version: 7.4.28
PHP binary path: /usr/bin/php7.4
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
cURL version: 7.52.1 libz 1.2.8 ssl OpenSSL/1.0.2u
zip: extension present, unzip present, 7-Zip not available
```

_In `composer.lock` we have this Flex entry:_

```JSON
        {
            "name": "symfony/flex",
            "version": "v1.18.5",
            "source": {
                "type": "git",
                "url": "https://github.com/symfony/flex.git",
                "reference": "10e438f53a972439675dc720706f0cd5c0ed94f1"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/symfony/flex/zipball/10e438f53a972439675dc720706f0cd5c0ed94f1",
                "reference": "10e438f53a972439675dc720706f0cd5c0ed94f1",
                "shasum": ""
            },
            "require": {
                "composer-plugin-api": "^1.0|^2.0",
                "php": ">=7.1"
            },
            "require-dev": {
                "composer/composer": "^1.0.2|^2.0",
                "symfony/dotenv": "^4.4|^5.0|^6.0",
                "symfony/filesystem": "^4.4|^5.0|^6.0",
                "symfony/phpunit-bridge": "^4.4.12|^5.0|^6.0",
                "symfony/process": "^4.4|^5.0|^6.0"
            },
            "type": "composer-plugin",
            "extra": {
                "class": "Symfony\\Flex\\Flex"
            },
            "autoload": {
                "psr-4": {
                    "Symfony\\Flex\\": "src"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Fabien Potencier",
                    "email": "fabien.potencier@gmail.com"
                }
            ],
            "description": "Composer plugin for Symfony",
            "support": {
                "issues": "https://github.com/symfony/flex/issues",
                "source": "https://github.com/symfony/flex/tree/v1.18.5"
            },
            "funding": [
                {
                    "url": "https://symfony.com/sponsor",
                    "type": "custom"
                },
                {
                    "url": "https://github.com/fabpot",
                    "type": "github"
                },
                {
                    "url": "https://tidelift.com/funding/github/packagist/symfony/symfony",
                    "type": "tidelift"
                }
            ],
            "time": "2022-02-16T17:26:46+00:00"
        }
```

... and in `symfony.lock` we have this Flex entry:

```JSON
    "symfony/flex": {
        "version": "1.0",
        "recipe": {
            "repo": "github.com/symfony/recipes",
            "branch": "master",
            "version": "1.0",
            "ref": "c0eeb50665f0f77226616b6038a9b06c03752d8e"
        },
        "files": [
            ".env"
        ]
    }
```

Are we doing something wrong or is this indeed a bug in Composer or Symfony Flex?

**Comment by nicolas-grekas** [comment] 2022-04-11 11:08
Closing as duplicate of #890

**Comment by wouterj** [comment] 2022-04-11 11:09
I guess you maybe also have Symfony Flex installed globally.

**Closed as completed by nicolas-grekas** 2022-04-11 11:08 UTC
