### ISSUE TITLE
Package download through Flex plugin fails/times out/gets stuck

### ISSUE THREAD

**Issue by keichinger** [symfony/flex#610] opened 2020-03-12 16:33 UTC
I've already had a brief conversation with @naderman (over on packagist.com) about this particular issue I'm currently facing. I'm running on macOS Catalina 10.15.3, PHP 7.4.3, Composer 1.10 (tried with 1.9 too), Symfony Flex 1.6.2 and I've tested it with two different projects that are using the very same (private) registry:

Every time I try to do a fresh full install (`rm -rf vendor/; rm composer.lock; composer install -vvv`), the installation will ultimately fail/halt due to some packages that can't be downloaded.

Running `composer install -vvv` shows that it literally just gets stuck on some (random) packages. It's always the same package that a particular project gets stuck downloading, but it's not the same (as in ProjectA gets stuck on PackageA, ProjectB gets stuck on PackageB). Downloading PackageA and PackageB through the browser also works fine. Since we have no firewall or proxy infrastructure in-place that might explain this problem, the last thing I tried is running `composer install --no-plugins` and voilá: It's installing just fine.

Now comes the strange thing: While writing this issue, I tried various Composer dependency requirements for the Flex plugin (note the `^`):
- `^1.6.2` initially: Didn't work in two different projects many times (in a row). Went to lunch.
- `1.6.0`: Worked after lunch.
- `1.6.1`: Worked as well.
- `1.6.2`: Worked, too
- `^1.6.2`: And curiously, this one then suddenly worked too

I could provide the output for the `-vvv` runs, though it only says that it's downloading a certain package from our private registry and then at some point fails – there's also no visible default TCP timeout or exception, it just says „Downloading <url>” and stays like that.

**Comment by nicolas-grekas** [comment] 2020-03-17 14:41
Honestly, I can't figure out how I can help here. I fear reproducing might be hard so that I wouldn't be able to understand what's going on really...

**Comment by keichinger** [comment] 2020-03-17 14:49
To be honest, I'm not even sure whether it's really Flex's fault since it „randomly” worked after all :/ I don't even know how I could help you figuring out what's going on other than providing traces, running debug versions and what not. Since Nils hasn't heard about this issue before (and it worked initially without any plugins), I thought it might be (somehow) related to Flex. However, I can totally understand when you say that this is a pure hail mary since there is no proper reproducer or obvious error.

To not waste anyones time (and since I'm apparently the only one having this issue right now?) I wouldn't be mad if we would just close this issue as a won't fix 🤷‍♂ Maybe it's worth investigating as soon as more people have run into this issue and maybe more sample data is available so it's easier to pin down the exact cause.

**Comment by nicolas-grekas** [comment] 2020-03-17 14:51
Composer 2 is using part of the code that I wrote for the HTTP in flex, I hope it doesn't have the issue :)

**Comment by keichinger** [comment] 2020-03-17 15:51
I've just installed composer 1.10.1 and ran `composer clear-cache; rm -rf vendor/; rm composer.lock; composer install -vvv` in order to properly test it against a known „defect” client project and it got stuck in the middle of downloading 134 packages (after Flex has been installed and initialized). Running the same commands with `--no-plugins` has worked, once again.
A different project that is also using Flex and „only” installs 123 packages it already gets stuck after installing Flex and then immediately updating the dependencies - the fix here is the same: running with `--no-plugins` has worked.
Another a smaller, non-Flex project with „only” 102 packages, downloading and installing has worked without a problem.

Nils told me that Packagist doesn't have any DDoS/firewall protection, though it still feels like I'm hitting a firewall. Maybe it's a general firewall from AWS, which might explain why a sudden burst of 134 parallel HTTP requests from the same origin doesn't go through. Running it without Flex all downloads will be executed in sequence, which might be sufficient why a DDoS protection/firewall doesn't recognize my attempt to install packages as an attack.

Since I'm working from home this week where I have no firewall or proxy installed, I think it's safe to say that we can rule out a local problem with our internet infrastructure (local firewall/proxy). 

Well :( No idea, really.

**Comment by stof** [comment] 2020-03-18 11:39
note that archive downloads don't go to packagist.org, but to github (or gitlab or bitbucket depending on where the package is hosted).

**Comment by nicolas-grekas** [comment] 2020-06-16 23:20
I'm closing here since now that flex is compatible with Composer 2, upgrading to it is the way to got. If the issue remains, please open an issue on composer instead :)

**Closed by nicolas-grekas** 2020-06-16 23:20 UTC

**Comment by keichinger** [comment] 2020-06-18 14:35
@nicolas-grekas thanks again for your hard work. I've just upgraded my composer to 2.0 alpha 1 and ran it against one of my known problem projects: It not only worked, it was blazingly fast. Composer v1 usually took like 3-5 minutes until it started downloading the packages - v2 finished within seconds.

v2.0 really seemed to have fixed my problem 🙌
