### ISSUE TITLE
Symfony\Flex\PackageJsonSynchronizer::addPackageJsonLink() must be of the type string, array given

### ISSUE THREAD

**Issue by samoussa** [symfony/flex#771] opened 2021-05-18 15:20 UTC
I'am trying to upgrade my symfony projet. Here is the error message :

Fatal error: Uncaught TypeError: Argument 1 passed to Symfony\Flex\PackageJsonSynchronizer::addPackageJsonLink() must be of the type string, array given, called in /builds/runm/promos/vendor/symfony/flex/src/PackageJsonSynchronizer.php on line 41 and defined in /builds/runm/promos/vendor/symfony/flex/src/PackageJsonSynchronizer.php:66

Thank you for your help

**Environnement** 
PHP : 7.4.19
composer : 2.0.13

```
php -d memory_limit=-1 composer.phar update
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "5.2.*"
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 29 updates, 0 removals
  - Downloading symfony/flex (v1.13.1)
  - Downloading symfony/http-foundation (v5.2.8)
  - Downloading symfony/var-dumper (v5.2.8)
  - Downloading symfony/error-handler (v5.2.8)
  - Downloading symfony/http-kernel (v5.2.8)
  - Downloading symfony/finder (v5.2.8)
  - Downloading symfony/dependency-injection (v5.2.8)
  - Downloading symfony/config (v5.2.8)
  - Downloading symfony/var-exporter (v5.2.8)
  - Downloading symfony/cache (v5.2.8)
  - Downloading doctrine/annotations (1.13.1)
  - Downloading doctrine/persistence (2.2.0)
  - Downloading symfony/string (v5.2.8)
  - Downloading symfony/console (v5.2.8)
  - Downloading laminas/laminas-code (4.3.0)
  - Downloading twig/twig (v3.3.2)
  - Downloading symfony/twig-bridge (v5.2.8)
  - Downloading symfony/translation (v5.2.8)
  - Downloading symfony/security-core (v5.2.8)
  - Downloading symfony/property-info (v5.2.8)
  - Downloading symfony/security-http (v5.2.8)
  - Downloading symfony/security-guard (v5.2.8)
  - Downloading symfony/security-bundle (v5.2.8)
  - Downloading symfony/form (v5.2.8)
  - Downloading mpdf/mpdf (v8.0.11)
  - Downloading symfony/http-client (v5.2.8)
  - Downloading symfony/maker-bundle (v1.31.1)
  - Downloading symfony/phpunit-bridge (v5.2.8)
  - Downloading symfony/web-profiler-bundle (v5.2.8)
  0/29 [>---------------------------]   0%
  1/29 [>---------------------------]   3%
 19/29 [==================>---------]  65%
 28/29 [===========================>]  96%
 29/29 [============================] 100%
 29/29 [============================] 100%  - Upgrading symfony/flex (v1.12.2 => v1.13.1): Extracting archive
  - Upgrading symfony/http-foundation (v5.2.7 => v5.2.8): Extracting archive
  - Upgrading symfony/var-dumper (v5.2.7 => v5.2.8): Extracting archive
  - Upgrading symfony/error-handler (v5.2.7 => v5.2.8): Extracting archive
  - Upgrading symfony/http-kernel (v5.2.7 => v5.2.8): Extracting archive
  - Upgrading symfony/finder (v5.2.4 => v5.2.8): Extracting archive
  - Upgrading symfony/dependency-injection (v5.2.7 => v5.2.8): Extracting archive
  - Upgrading symfony/config (v5.2.7 => v5.2.8): Extracting archive
  - Upgrading symfony/var-exporter (v5.2.7 => v5.2.8): Extracting archive
  - Upgrading symfony/cache (v5.2.7 => v5.2.8): Extracting archive
  - Upgrading doctrine/annotations (1.12.1 => 1.13.1): Extracting archive
  - Upgrading doctrine/persistence (2.1.0 => 2.2.0): Extracting archive
  - Upgrading symfony/string (v5.2.6 => v5.2.8): Extracting archive
  - Upgrading symfony/console (v5.2.7 => v5.2.8): Extracting archive
  - Upgrading laminas/laminas-code (4.2.2 => 4.3.0): Extracting archive
  - Upgrading twig/twig (v3.3.0 => v3.3.2): Extracting archive
  - Upgrading symfony/twig-bridge (v5.2.7 => v5.2.8): Extracting archive
  - Upgrading symfony/translation (v5.2.7 => v5.2.8): Extracting archive
  - Upgrading symfony/security-core (v5.2.7 => v5.2.8): Extracting archive
  - Upgrading symfony/property-info (v5.2.7 => v5.2.8): Extracting archive
  - Upgrading symfony/security-http (v5.2.7 => v5.2.8): Extracting archive
  - Upgrading symfony/security-guard (v5.2.4 => v5.2.8): Extracting archive
  - Upgrading symfony/security-bundle (v5.2.7 => v5.2.8): Extracting archive
  - Upgrading symfony/form (v5.2.7 => v5.2.8): Extracting archive
  - Upgrading mpdf/mpdf (v8.0.10 => v8.0.11): Extracting archive
  - Upgrading symfony/http-client (v5.2.7 => v5.2.8): Extracting archive
  - Upgrading symfony/maker-bundle (v1.31.0 => v1.31.1): Extracting archive
  - Upgrading symfony/phpunit-bridge (v5.2.7 => v5.2.8): Extracting archive
  - Upgrading symfony/web-profiler-bundle (v5.2.7 => v5.2.8): Extracting archive
  0/18 [>---------------------------]   0%
 10/18 [===============>------------]  55%
 17/18 [==========================>-]  94%
 18/18 [============================] 100%Generating optimized autoload files
Class App\Tests\Controller\UserControllerTest located in ./tests/Controllers/UserControllerTest.php does not comply with psr-4 autoloading standard. Skipping.
Class App\Tests\Controller\PromotionControllerTest located in ./tests/Controllers/PromotionControllerTest.php does not comply with psr-4 autoloading standard. Skipping.
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
126 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
What about running composer global require symfony/thanks && composer thanks now?
This will spread some 💖  by sending a ★  to the GitHub repositories of your fellow package maintainers.
Fatal error: Uncaught TypeError: Argument 1 passed to Symfony\Flex\PackageJsonSynchronizer::addPackageJsonLink() must be of the type string, array given, called in /builds/runm/promos/vendor/symfony/flex/src/PackageJsonSynchronizer.php on line 41 and defined in /builds/runm/promos/vendor/symfony/flex/src/PackageJsonSynchronizer.php:66
Stack trace:
#0 /builds/runm/promos/vendor/symfony/flex/src/PackageJsonSynchronizer.php(41): Symfony\Flex\PackageJsonSynchronizer->addPackageJsonLink(Array)
#1 phar:///builds/runm/promos/composer.phar/src/Composer/Plugin/PluginManager.php(221) : eval()'d code(598): Symfony\Flex\PackageJsonSynchronizer->synchronize(Array)
#2 phar:///builds/runm/promos/composer.phar/src/Composer/Plugin/PluginManager.php(221) : eval()'d code(488): Symfony\Flex\Flex_composer_tmp0->synchronizePackageJson('/builds/runm/pr...')
#3 phar:///builds/runm/promos/composer.phar/src/Composer/Plugin/PluginManager.php(221) : eval()'d code(396): Symfony\Flex\Flex_composer_tmp0->install(Object(Composer\Script\Event))
#4 [inter in /builds/runm/promos/vendor/symfony/flex/src/PackageJsonSynchronizer.php on line 66
```

**composer.json**
```
{
    "type": "project",
    "license": "proprietary",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "php": ">=7.2.5",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "claviska/simpleimage": "^3.6",
        "composer/package-versions-deprecated": "1.11.99.1",
        "doctrine/doctrine-bundle": "^2.2",
        "doctrine/doctrine-migrations-bundle": "^3.0",
        "doctrine/orm": "^2.8",
        "easycorp/easyadmin-bundle": "3.2.1",
        "kraken-io/kraken-php": "^1.6",
        "mpdf/mpdf": "^8.0",
        "nyholm/psr7": "^1.3",
        "phpoffice/phpspreadsheet": "^1.16",
        "phpoffice/phpword": "^0.18.0",
        "sensio/framework-extra-bundle": "^5.6",
        "sentry/sentry-symfony": "^4.0",
        "symfony/apache-pack": "^1.0",
        "symfony/console": "5.2.*",
        "symfony/debug-bundle": "5.2.*",
        "symfony/dotenv": "5.2.*",
        "symfony/flex": "^1.3.1",
        "symfony/framework-bundle": "5.2.*",
        "symfony/mime": "5.2.*",
        "symfony/monolog-bundle": "^3.6",
        "symfony/security-bundle": "5.2.*",
        "symfony/stopwatch": "5.2.*",
        "symfony/swiftmailer-bundle": "^3.5",
        "symfony/twig-bundle": "^5.2",
        "symfony/validator": "5.2.*",
        "symfony/webpack-encore-bundle": "^1.9",
        "symfony/yaml": "5.2.*",
        "vich/uploader-bundle": "^1.16"
    },
    "require-dev": {
        "dama/doctrine-test-bundle": "^6.5",
        "doctrine/doctrine-fixtures-bundle": "^3.4",
        "friendsofphp/php-cs-fixer": "^2.16",
        "phpunit/phpunit": "^9.2",
        "symfony/browser-kit": "5.1.*",
        "symfony/css-selector": "5.2.*",
        "symfony/maker-bundle": "^1.25",
        "symfony/phpunit-bridge": "^5.2",
        "symfony/var-dumper": "5.2.*",
        "symfony/web-profiler-bundle": "^5.2"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ],
        "commit": [
            "php-cs-fixer fix",
            "phpunit"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "5.2.*"
        }
    }
}
```

**Comment by nicolas-grekas** [comment] 2021-05-18 15:23
Duplicate of #770

**Closed by nicolas-grekas** 2021-05-18 15:23 UTC
