### ISSUE TITLE
Flex tries to inspect vendor/ after Composer has already removed the package

### ISSUE THREAD

**Issue by dkarlovi** [symfony/flex#73] opened 2017-05-07 16:13 UTC
Basically this:

    $ SYMFONY_ENDPOINT=https://symfony.sh/r/contrib/15 composer remove dkarlovi/symfony-flex-docker
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Package operations: 0 installs, 0 updates, 1 removal
      - Removing dkarlovi/symfony-flex-docker (0.1.3)
        Auto-unconfiguring "dkarlovi/symfony-flex-docker"
        Removing configuration and files
    
    Removal failed, reverting ./composer.json to its original content.
    
                                                                                                                                             
      [UnexpectedValueException]                                                                                                             
      RecursiveDirectoryIterator::__construct(/home/dado/Development/symfony-skeleton/vendor/dkarlovi/symfony-flex-docker/.infra/): failed   
      to open dir: No such file or directory

**Comment by fabpot** [comment] 2017-08-09 13:02
Thinking about this issue a bit more, I'm wondering if copying files from a package is really a feature we want to keep.

**Comment by nicolas-grekas** [comment] 2020-12-15 17:29
Closing as staled. Please provide a PR ideally if you can.

**Closed by nicolas-grekas** 2020-12-15 17:29 UTC

**Comment by tperunsky** [comment] 2022-01-03 12:48
@nicolas-grekas 
I would like to reopen this issue to discuss options. 

The problem is described in more detail here: https://github.com/symfony/flex/issues/604 
Although it seems to me that the root cause is that `\Symfony\Flex\Configurator\CopyFromPackageConfigurator::removeFilesFromDir()` iterates over files in the package to figure out what to delete from the project. This is probably to make sure Flex doesn't delete files/folders which weren't copied from the package by the recipe in the first place. However, the package no longer exists in `/vendor` when this code runs.

In short, 
1. on composer install the `copy-from-package` stuff is copied (eg FE assets) 
2. on composer remove there's an error and as a result the composer package is removed, but the recipe is still in symfony.lock (bundle.php entry and `copy-from-recipe` files get removed correctly)

Unless I'm missing something, the `copy-from-package` functionality is broken at the moment. 

@fabpot mentioned in a comment above that this functionality is in question, but 4 years later it's still there, although not fully working, as evidenced by this issue. 
IMO it should either be removed or fixed - at the very least removing a package shouldn't result in an error. Maybe instead of the error, there should be a message explaining that files copied from the package have to be removed manually. 

I can provide a PR if you think it makes sense to pursue this.

**Comment by nicolas-grekas** [comment] 2022-01-03 15:30
Please provide a PR if you can yes!

**Comment by tperunsky** [comment] 2022-01-04 13:06
@nicolas-grekas 
There you go https://github.com/symfony/flex/pull/847
