### ISSUE TITLE
Composer create-project: no output from "post-create-project-cmd" as soon as symfony/flex is required

### ISSUE THREAD

**Issue by aleksblendwerk** [symfony/flex#675] opened 2020-09-13 09:58 UTC
I am currently working on a custom version of `symfony/website-skeleton` to set some more defaults for new projects in our company. The modified `composer.json` also includes a couple of commands for composer's `post-create-project-cmd` event in the `scripts` section.

When I call `composer create-project [...]` the output ends after the recipes' post-install notes (or after the message `Run composer recipes at any time to see the status of your Symfony recipes` if I further reduce the required dependencies). The commands in `post-create-project-cmd` are executed but their output is never shown.

I first thought this might be a composer problem but I reduced the `composer.json` file to test this and it seems to happen as soon as `symfony/flex` is required.

The current file I am testing with looks like this:

```
{
    "name": "test/post-create-project-cmd-is-silent",
    "type": "project",
    "description": "Testing if post-create-project-cmd is silent",
    "require": {
        "php": ">=7.4",
        "symfony/flex": "^1.3.1"
    },
    "scripts": {
        "post-create-project-cmd": [
            "yarn install"
        ]
    }
}
```

Or is this intended?

**Comment by maxhelias** [comment] 2020-09-14 09:07
Which composer version do you use ?

**Comment by aleksblendwerk** [comment] 2020-09-14 12:56
> Which composer version do you use ?

`Composer version 1.10.13 2020-09-09 11:46:34`

**Comment by nicolas-grekas** [comment] 2020-09-14 14:39
Can you please provide a precise reproducer? I tried with composer 2 and it worked as expected (and I can't make composer 1 work right now, that's why the reproducer would help).
Thanks

**Comment by nicolas-grekas** [comment] 2020-12-15 16:47
Closing as I cannot reproduce. Please provide step by step instructions if you can, maybe a ZIP file or a gist also?

**Closed by nicolas-grekas** 2020-12-15 16:47 UTC
