### ISSUE TITLE
CopyFromRecipeConfigurator,  mkdir no such file or directory 

### ISSUE THREAD

**Issue by preja** [symfony/flex#301] opened 2018-01-17 12:11 UTC
While installing symfony skeleton I've got:
Any Idea?
<pre>
Symfony operations: 4 recipes (b240144ccf37736535bed672c3fd3f57)
  - Configuring symfony/flex (>=1.0): From github.com/symfony/recipes:master
    Setting configuration and copying files
Reading ./composer.json
Loading config file C:/Users/pawel/AppData/Roaming/Composer/config.json
Loading config file C:/Users/pawel/AppData/Roaming/Composer/auth.json
Loading config file ./composer.json
Reading C:/Users/pawel/AppData/Roaming/Composer/composer.json
Loading config file C:/Users/pawel/AppData/Roaming/Composer/config.json
Loading config file C:/Users/pawel/AppData/Roaming/Composer/auth.json
Loading config file C:/Users/pawel/AppData/Roaming/Composer/composer.json
Loading config file C:\Users\pawel\AppData\Roaming\Composer/auth.json
Reading C:\Users\pawel\AppData\Roaming\Composer/auth.json
Reading D:\htdocs\al/vendor/composer/installed.json

  [ErrorException]
  mkdir(): No such file or directory

Exception trace:
 () at D:\htdocs\assetlife\vendor\symfony\flex\src\Configurator\CopyFromRecipeConfigurator.php:62
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 mkdir() at D:\htdocs\assetlife\vendor\symfony\flex\src\Configurator\CopyFromRecipeConfigurator.php:62
 Symfony\Flex\Configurator\CopyFromRecipeConfigurator->copyFile() at D:\htdocs\assetlife\vendor\symfony\flex\src\Configurator\CopyFromRecipeConfigurator.php:40
 Symfony\Flex\Configurator\CopyFromRecipeConfigurator->copyFiles() at D:\htdocs\assetlife\vendor\symfony\flex\src\Configurator\CopyFromRecipeConfigurator.php:24
 Symfony\Flex\Configurator\CopyFromRecipeConfigurator->configure() at D:\htdocs\assetlife\vendor\symfony\flex\src\Configurator.php:52
 Symfony\Flex\Configurator->install() at D:\htdocs\assetlife\vendor\symfony\flex\src\Flex.php:279
 Symfony\Flex\Flex->update() at n/a:n/a
 call_user_func() at phar://C:/Users/pawel/AppData/Local/ComposerSetup/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:171
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar://C:/Users/pawel/AppData/Local/ComposerSetup/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:96
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar://C:/Users/pawel/AppData/Local/ComposerSetup/bin/composer.phar/src/Composer/Installer.php:322
 Composer\Installer->run() at phar://C:/Users/pawel/AppData/Local/ComposerSetup/bin/composer.phar/src/Composer/Command/CreateProjectCommand.php:191
 Composer\Command\CreateProjectCommand->installProject() at phar://C:/Users/pawel/AppData/Local/ComposerSetup/bin/composer.phar/src/Composer/Command/CreateProjectCommand.php:143
 Composer\Command\CreateProjectCommand->execute() at phar://C:/Users/pawel/AppData/Local/ComposerSetup/bin/composer.phar/vendor/symfony/console/Command/Command.php:242
 Symfony\Component\Console\Command\Command->run() at phar://C:/Users/pawel/AppData/Local/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:842
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/Users/pawel/AppData/Local/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at phar://C:/Users/pawel/AppData/Local/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:251
 Composer\Console\Application->doRun() at phar://C:/Users/pawel/AppData/Local/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar://C:/Users/pawel/AppData/Local/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar://C:/Users/pawel/AppData/Local/ComposerSetup/bin/composer.phar/bin/composer:58
 require() at C:\Users\pawel\AppData\Local\ComposerSetup\bin\composer.phar:24

</pre>

**Comment by kristoftorfs** [comment] 2018-01-17 12:28
Duplicate of #298, which already has a PR as well.

**Closed** 2018-01-17 13:40 UTC
