### ISSUE TITLE
PHP Fatal error: Allowed memory size of xxx bytes exhausted on "composer update --no-dev --prefer-dist --optimize-autoloader"

### ISSUE THREAD

**Issue by k00ni** [symfony/flex#530] opened 2019-07-02 14:55 UTC
## Summary

I get an error with composer, but i assume its Flex related, because it works until a certain flex version (above 1.2.7 somewhere). The error occurs when running `composer update` with certain parameters. Can you tell me, if i made a mistake or is there something buggy here?

Thanks for your time.

### Error occurs with the following flex versions

I could reproduce the error with the following Flex versions:

* 1.4.1
* 1.3.1

But it **works** with the following Flex versions:
* 1.2.5
* 1.2.7

### Composer diagnose result

Here is the `compose diagnose` output:

> Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
Composer version: **1.8.6**
PHP version: **7.2.19**
PHP binary path: /usr/local/bin/php

### Composer command which raised the error

> composer clearcache && rm -rf vendor/* && composer update --no-dev --prefer-dist --optimize-autoloader

(also removed the composer.lock file before running the command)

#### Output of the composer command

> Cache directory does not exist (cache-vcs-dir): 
Clearing cache (cache-repo-dir): /home/backbone/.composer/cache/repo
Clearing cache (cache-files-dir): /home/backbone/.composer/cache/files
Clearing cache (cache-dir): /home/backbone/.composer/cache
All caches cleared.
Loading composer repositories with package information
Updating dependencies
Package operations: 55 installs, 0 updates, 0 removals
>  \- Installing symfony/flex (v1.4.1): Downloading (100%)         
Loading composer repositories with package information
Updating dependencies
PHP Fatal error: **Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes)** in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 49
Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 49
Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.Segmentation fault (core dumped)

#### Here is only the error message

> PHP Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 49
Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 49
Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.Segmentation fault (core dumped)

### How to reproduce

Run 

> composer clearcache && rm -rf vendor/* && composer update --no-dev --prefer-dist --optimize-autoloader

with the following `composer.json`:

```json
{
    "license": "proprietary",
    "require": {
        "php": "^7.2.12",
        "ext-iconv": "*",
        "erusev/parsedown": "^1.7",
        "genkgo/mail": ">=2.2",
        "jaybizzle/crawler-detect": "^1.2",
        "league/iso3166": "^2.1.1",
        "php-curl-class/php-curl-class": "^8.5.0",
        "pietercolpaert/hardf": "^0.1.3",
        "sensio/framework-extra-bundle": "^5.1",
        "symfony/apache-pack": "^1.0",
        "symfony/asset": "^4.3",
        "symfony/console": "^4.3",
        "symfony/dotenv": "^4.3",
        "symfony/flex": "1.4.1",
        "symfony/framework-bundle": "^4.3",
        "symfony/monolog-bundle": "^3.1",
        "symfony/property-access": "^4.3",
        "symfony/serializer": "^4.3",
        "symfony/twig-bridge": "^4.3",
        "symfony/twig-bundle": "^4.3",
        "symfony/yaml": "^4.3",
        "twig/extensions": "^1.5",
        "twig/twig": "^2.5"
    },
    "require-dev": {
        "phpunit/phpunit": "^7.3",
        "php-mock/php-mock": "^2.0",
        "php-mock/php-mock-phpunit": "^2.1",
        "symfony/stopwatch": "^4.3",
        "symfony/web-profiler-bundle": "^4.3",
        "symplify/easy-coding-standard": "*",
        "wmde/psr-log-test-doubles": "^2.2"
    },
    "prefer-stable": true,
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "Backbone\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Backbone\\Tests\\": "tests/"
        }
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd",
            "assets:install --symlink --relative %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "id": "XXXX",
            "allow-contrib": false
        }
    }
}
```

**Comment by nicolas-grekas** [comment] 2019-07-05 10:04
I think this will be solved by next composer version, once https://github.com/composer/composer/pull/8200 is tagged.
The issue is that flex reboots the SAT solver to enforce it extra constraints, but cannot free memory from the previous run, so that memory explodes.
Please try again with a patched composer. Any better?

**Comment by nicolas-grekas** [comment] 2019-07-05 10:05
Note that there is a workaround, which is doing it in two steps:
- composer ins (with composer.lock)
- composer up

**Comment by k00ni** [comment] 2019-07-05 10:29
Hi @nicolas-grekas, thanks for the response.

> Please try again with a patched composer. Any better?

I can do that and will post my findings here, no problem.

**Comment by nicolas-grekas** [comment] 2019-07-15 11:37
Closing as the issue is not in flex and a workaround has been provided.

**Closed by nicolas-grekas** 2019-07-15 11:37 UTC

**Comment by ravinayag** [comment] 2020-05-14 16:06
I faced this problem relate to memory allocaton aand similar to this when i do cache:clear:
PHP Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/user/public_html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php

Hence tried to update the mautic version,  2.16.2,   the update was success but the memory error not gone. 

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 495616 bytes) in /home/user/public_html/s/vendor/symfony/translation/Translator.php on line 353


  [Symfony\Component\Debug\Exception\OutOfMemoryException]
  Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 495616 bytes)


Exception trace:
 () at /home/user/public_html/s/vendor/symfony/translation/Translator.php:353

the Solution :  increase  memory_limit in the php.ini file. 
memory_limit=1024M

check which php ini config is using by:
php -i | grep "php.ini"
once it updated restart the Apache services.

**Comment by stof** [comment] 2020-05-14 16:51
Things happening during cache clear are totally different.

**Comment by ravinayag** [comment] 2020-05-14 17:23
I think the memory related error will go away by increasing the memory_limit  in php.ini.  I recommend to try this step before any upgrade.

**Comment by stof** [comment] 2020-05-14 17:27
@ravinayag *your* memory error is not happening when running Flex, but when running your Symfony project's `cache:clear` command. It is **not** the one discussed in this (closed) issue.

**Comment by djimrangarleita** [comment] 2023-11-12 06:26
I add this comment here because this is the first page that pops out for the search term _"Php symfony: Fatal error Allowed memory size of xx bytes exhausted"_.

I recently encountered this issue with **Symfony 6.3.7** (not related to composer/flex though). It takes me a couple of days to solve because I didn't find the right resource on the internet that could help.

In general, increasing the `memory_limit` is not the best solution (btw, I've set mine to -1 and increased the max_x_time, but nothing). You'll need to investigate to find the root cause of the issue.

For me, the `$kernel->handle($request);` in public/index.php could not terminate its execution or throw and error, therefore there were no symfony dump/log neither in the CLI nor in the browser, I just got `HTTP ERROR 500` from the browser. I've followed the $kernel->handle function until PhpDumper.php in vendor with a bunch of dumps and then used `git diff`.
It turns out there is a `circular reference` exception that has not been detected/controlled by the ServiceCircularReferenceException and I have no idea why. I tried to reproduce the same error with **Symfony 5.4**, **Symfony 6.3.8** and it has been properly handled.

Finally, thanks to git diff, I removed the dependency injections that led to the endless recursion and everything is now running smoothly with just `128M` of memory.

Code example and screenshot for my case(all projects in debug mode on localhost):

```php
<?php

namespace App\MyModule\Service;

use App\Service\XService\Service1;

class Service2
{
    public function __construct(private Service1 $service1)
    {
    }
}
```

```php
<?php

namespace App\Service\XService;

use App\MyModule\Service\Service2;

class Service1
{
    public function __construct(private Service2 $service2)
    {
    }
}
```
**Image with Symfony 6.3.8, exception detected**
![Screenshot 2023-11-12 at 9 23 50 AM](https://github.com/symfony/flex/assets/33844006/b98c75ce-2235-44d5-84da-f0d9db86497e)

**Image with Symfony 6.3.7, exception not detected, memory exhausted**
![Screenshot 2023-11-12 at 9 24 07 AM](https://github.com/symfony/flex/assets/33844006/1701874a-1bd8-4f77-89b8-f373486e40d4)
