### ISSUE TITLE
bundles.php not updated if parent package is updated

### ISSUE THREAD

**Issue by emulienfou** [symfony/flex#191] opened 2017-10-20 15:00 UTC
Hi there,
actually in development phase for my project, I think there is a bug in Flex because my file `bundles.php` won't be updated if I update a required package.

---

_Let me explain this!_
I've got a package named `demo/theme-bundle` who has been updated and a new dependency has been added in `composer.json` file.

In my current projet who requires `demo/theme-bundle`, I ask Composer to update all packages with `composer update` command, and composer do is job!

However, Flex do not update my `bundles.php` file, with the new dependency!

So I presume if i delete the `bundles.php` file and execute `composer update` my file will be re-created and updated, but no, nothing `bundles.php` file is even no created! **Is it a bug?**

So I figured out that I need to remove all my **vendor/*** directories, the file **composer.lock** and execute `composer install`. After that, `bundles.php` is re-created with the new dependency added in `demo/theme-bundle`.
**Is it also a bug?**

Thanks for your help!

**Comment by Pierstoval** [comment] 2017-10-22 16:33
You have to manually `require` the new package, because Flex doesn't trigger on `composer update`, IIUC

**Comment by fabpot** [comment] 2018-02-19 11:22
Closing as I'm not able to reproduce the issue.

If you remove bundles.php, it won't be re-created, the file is updated when new packages are added only.

**Closed by fabpot** 2018-02-19 11:22 UTC
