### ISSUE TITLE
Disabling specific recipes for custom skeleton

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/flex#554] opened 2019-08-21 17:26 UTC
We in sulu have a custom skeleton where the [some bundles](https://github.com/sulu/sulu-minimal/blob/develop/config/bundles.php) are preconfigured for the way we need them. How can I disabled that it will execute recipes for this exist installed dependencies?

**Comment by nicolas-grekas** [comment] 2019-08-21 17:55
You can commit a symfony.lock with the right content.

**Comment by alexander-schranz** [comment] 2019-08-21 18:12
@nicolas-grekas but the dependencies version are related to the php version so providing a symfony.lock will force to provide also a composer.lock and force that user to use the same php version as this file are created for or?

Or could i just create a symfony.lock without versions to avoid this recipes? e.g.:

```
{
    "symfony/framework-bundle": {},
    "doctrine/doctrine-bundle": {}
}
```

**Comment by dunglas** [comment] 2019-08-21 18:25
In API Platform, we use [a shell script](https://github.com/api-platform/api-platform/blob/master/update-deps.sh) editing the files generate by the recipes after their installation. As we provide a Docker setup, and `composer.lock` and `symfony.lock` in our skeleton, we don't have the problem regarding the PHP version. However, this idea could maybe be generalized: you can maybe provide a Composer script (in your skeleton) that will be executed after Flex and will tweak the files generated by the recipes?

**Comment by esserj** [comment] 2020-06-19 07:09
Yeah, we also have similar issues, where we have created packages and these packages have a set of bundles together with specific configuration to their use case, like a package with multi-lingual support one that hes config for none multi-lingual support, etc... this allows us to craft recipes without having to use skeleton applications, unfortunately at the moment we always have to force install their recipes because flex first installs the bundle's recipes and only then the package, preventing of from predefining config for bundles in the package, this might be by design though, but would be a great addition to flex if we could have 3 packages all with the same bundles, but with different configurations. The main raison skeletons dont work is because you may want to combine 2 packages like this and you can only do create project once

**Comment by nicolas-grekas** [comment] 2020-12-15 17:42
> Or could i just create a symfony.lock without versions to avoid this recipes? e.g.:

We could support something like this yes: entries in symfony.lock that would tell "always skip recipes for this package".

Anyone up to give it a try?

**Comment by nicolas-grekas** [comment] 2021-09-21 17:01
I'm closing here because I think #803 provides a solution for that: define your own flex endpoint.

**Closed by nicolas-grekas** 2021-09-21 17:01 UTC
