### ISSUE TITLE
TwigBundle installed to all envs on "composer require --dev profile-pack"

### ISSUE THREAD

**Issue by VolCh** [symfony/flex#134] opened 2017-07-30 10:04 UTC
Expected bundles.php in the case when twig not installed yet:
```
return [
// ...
    'Symfony\Bundle\WebProfilerBundle\WebProfilerBundle' => ['dev' => true, 'test' => true],
    'Symfony\Bundle\TwigBundle\TwigBundle' => ['dev' => true, 'test' => true],
];
```
Actual: 
```
return [
// ...
    'Symfony\Bundle\WebProfilerBundle\WebProfilerBundle' => ['dev' => true, 'test' => true],
    'Symfony\Bundle\TwigBundle\TwigBundle' => ['all' => true],
];
```
The same about twig.yml - it placed to common packages config directory instead expected {dev,test} subdirs.

I don't sure that the problem is a problem of profiler-pack or twig recipe - I can't find any description or example recipe explains how to detect `--dev` option in `composer require` in a recipe or a pack and make changes properly.

I think flex itself should detect `--dev` and automatically customize the recipe declaration on common (actually) manifests and/or use explicitly described `dev` section somewhere in it.

**Comment by javiereguiluz** [comment] 2017-07-30 10:15
Maybe is a duplicate of #80? (which was closed but not fixed)

**Comment by VolCh** [comment] 2017-07-31 05:03
Partially. That issue is about common bundle, this issue is about recipe/pack. Common part is detecting and properly handling `--dev` option.

**Comment by fabpot** [comment] 2017-08-01 06:37
#80 was closed and fixed
Here, the limitation comes from the way Composer works. Nothing we can do unfortunately.

**Comment by fabpot** [comment] 2017-08-01 06:38
#80 was closed and fixed (as demonstrated by this very report)
Here, the limitation comes from the way Composer works. Nothing we can do unfortunately.

**Closed by fabpot** 2017-08-01 06:37 UTC
